import { useCallback, useEffect, useState } from 'react'
import { Languages, Pencil, Plus, Power } from 'lucide-react'
import { Modal } from '@/components/Modal'
import { EmptyState, PageContainer, PageError, PageHeader, PageLoading } from '@/components/PageStates'
import { Badge, Button, Input, Label, SurfaceCard } from '@/components/ui'
import { normalizeApiError } from '@/lib/apiError'
import { createLanguage, listLanguages, setLanguageActive, updateLanguage } from './languageApi'
import type { CreateLanguageInput, Language, LanguageDirection, LanguagePage } from './languageTypes'

const empty: LanguagePage = { data: [], meta: { total: 0, page: 1, limit: 20, totalPages: 0, hasNext: false, hasPrevious: false } }
export function LanguageAdminPage() {
  const [result, setResult] = useState(empty), [loading, setLoading] = useState(true), [error, setError] = useState<string|null>(null), [search, setSearch] = useState(''), [page, setPage] = useState(1), [editing, setEditing] = useState<Language|'create'|null>(null), [busy, setBusy] = useState(false), [formError, setFormError] = useState<string|null>(null), [lifecycleTarget, setLifecycleTarget] = useState<Language|null>(null)
  const load = useCallback(async()=>{ setLoading(true); setError(null); try { setResult(await listLanguages({ page, limit: 20, search: search || undefined }, true)) } catch(e){ setError(normalizeApiError(e).message) } finally { setLoading(false) } },[page,search])
  useEffect(()=>{ void load() },[load])
  async function save(input: CreateLanguageInput){ setBusy(true); setFormError(null); try { editing === 'create' ? await createLanguage(input) : editing && await updateLanguage(editing.id, { name: input.name, nativeName: input.nativeName, direction: input.direction }); setEditing(null); await load() } catch(e){ setFormError(normalizeApiError(e).message) } finally { setBusy(false) } }
  async function toggle(language: Language){ setBusy(true); try { await setLanguageActive(language.id,!language.isActive); setLifecycleTarget(null); await load() } catch(e){ setError(normalizeApiError(e).message) } finally { setBusy(false) } }
  return <PageContainer><PageHeader title="مدیریت زبان‌ها" description="کاتالوگ سراسری زبان‌های محتوایی سامانه" actions={<Button onClick={()=>setEditing('create')}><Plus size={18}/>زبان جدید</Button>}/><form className="workspace-toolbar" onSubmit={e=>{e.preventDefault();setPage(1);setSearch(new FormData(e.currentTarget).get('search')?.toString().trim()??'')}}><Input name="search" aria-label="جست‌وجوی زبان" placeholder="نام، نام بومی یا کد"/><Button type="submit" variant="secondary">جست‌وجو</Button></form>{loading?<PageLoading label="در حال دریافت زبان‌ها…"/>:error?<PageError description={error} onRetry={()=>void load()}/>:result.data.length===0?<EmptyState title="زبانی یافت نشد" description="اولین زبان را به کاتالوگ اضافه کنید." icon={<Languages size={30}/>}/>:<><div className="workspace-grid">{result.data.map(language=><SurfaceCard className="workspace-card language-card" key={language.id}><header><strong dir={language.direction==='RTL'?'rtl':'ltr'}>{language.nativeName}</strong><Badge tone={language.isActive?'success':'warning'}>{language.isActive?'فعال':'غیرفعال'}</Badge></header><div><h2>{language.name}</h2><code dir="ltr">{language.code} · {language.direction}</code></div><footer><Button variant="ghost" onClick={()=>setEditing(language)}><Pencil size={17}/>ویرایش</Button><Button variant="ghost" disabled={busy} onClick={()=>setLifecycleTarget(language)}><Power size={17}/>{language.isActive?'غیرفعال‌سازی':'فعال‌سازی'}</Button></footer></SurfaceCard>)}</div><nav className="workspace-pagination"><Button variant="secondary" disabled={!result.meta.hasPrevious} onClick={()=>setPage(p=>p-1)}>قبل</Button><span>صفحه {page} از {Math.max(result.meta.totalPages,1)}</span><Button variant="secondary" disabled={!result.meta.hasNext} onClick={()=>setPage(p=>p+1)}>بعد</Button></nav></>}{editing&&<Modal title={editing==='create'?'افزودن زبان':'ویرایش زبان'} onClose={()=>!busy&&setEditing(null)}><LanguageForm language={editing==='create'?undefined:editing} busy={busy} error={formError} onSubmit={save} onCancel={()=>setEditing(null)}/></Modal>}{lifecycleTarget&&<Modal title={lifecycleTarget.isActive?'غیرفعال‌سازی زبان':'فعال‌سازی زبان'} description={lifecycleTarget.isActive?'ارجاع‌های موجود حفظ می‌شوند، اما زبان برای انتخاب جدید در دسترس نخواهد بود.':'زبان دوباره برای انتخاب‌های جدید قابل استفاده می‌شود.'} onClose={()=>!busy&&setLifecycleTarget(null)}><div className="archive-confirmation"><footer><Button variant="secondary" onClick={()=>setLifecycleTarget(null)}>انصراف</Button><Button variant={lifecycleTarget.isActive?"danger":"primary"} disabled={busy} onClick={()=>void toggle(lifecycleTarget)}>تأیید</Button></footer></div></Modal>}</PageContainer>
}

function LanguageForm({language,busy,error,onSubmit,onCancel}:{language?:Language;busy:boolean;error:string|null;onSubmit:(input:CreateLanguageInput)=>Promise<void>;onCancel:()=>void}) { const [code,setCode]=useState(language?.code??''),[name,setName]=useState(language?.name??''),[nativeName,setNativeName]=useState(language?.nativeName??''),[direction,setDirection]=useState<LanguageDirection>(language?.direction??'LTR'); return <form className="workspace-form" onSubmit={e=>{e.preventDefault();void onSubmit({code:code.trim(),name:name.trim(),nativeName:nativeName.trim(),direction})}}><Label>کد BCP-47<Input dir="ltr" required maxLength={35} readOnly={Boolean(language)} value={code} onChange={e=>setCode(e.target.value)}/></Label><Label>نام<Input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></Label><Label>نام بومی<Input required maxLength={120} value={nativeName} onChange={e=>setNativeName(e.target.value)}/></Label><Label>جهت<select className="ui-input" value={direction} onChange={e=>setDirection(e.target.value as LanguageDirection)}><option value="LTR">چپ به راست</option><option value="RTL">راست به چپ</option></select></Label>{error&&<div className="form-error">{error}</div>}<footer><Button type="button" variant="secondary" onClick={onCancel}>انصراف</Button><Button type="submit" disabled={busy}>{busy?'در حال ذخیره…':'ذخیره'}</Button></footer></form> }

