import { useCallback, useEffect, useState } from 'react'
import { Pencil, Plus, Power, Tags, Trash2 } from 'lucide-react'
import { Modal } from '@/components/Modal'
import { EmptyState, PageContainer, PageError, PageHeader, PageLoading } from '@/components/PageStates'
import { Badge, Button, Input, Label, SurfaceCard } from '@/components/ui'
import { listAllSelectableIntelligenceDomains } from '@/features/intelligence-domains/intelligenceDomainApi'
import type { IntelligenceDomain } from '@/features/intelligence-domains/intelligenceDomainTypes'
import { listAllSelectableLanguages } from '@/features/languages/languageApi'
import type { Language } from '@/features/languages/languageTypes'
import { normalizeApiError } from '@/lib/apiError'
import { createTopic, listTopics, setTopicActive, updateTopic } from './topicApi'
import type { CreateTopicInput, Topic, TopicAliasInput, TopicPage } from './topicTypes'

const empty:TopicPage={data:[],meta:{total:0,page:1,limit:20,totalPages:0,hasNext:false,hasPrevious:false}}
export function TopicAdminPage(){
  const[result,setResult]=useState(empty),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[search,setSearch]=useState(''),[page,setPage]=useState(1),[editing,setEditing]=useState<Topic|'create'|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState<string|null>(null),[lifecycle,setLifecycle]=useState<Topic|null>(null)
  const load=useCallback(async()=>{setLoading(true);setError(null);try{setResult(await listTopics({page,limit:20,search:search||undefined},true))}catch(e){setError(normalizeApiError(e).message)}finally{setLoading(false)}},[page,search]);useEffect(()=>{void load()},[load])
  async function save(input:CreateTopicInput){setBusy(true);setFormError(null);try{editing==='create'?await createTopic(input):editing&&await updateTopic(editing.id,{name:input.name,description:input.description||null,domainIds:input.domainIds,aliases:input.aliases});setEditing(null);await load()}catch(e){setFormError(normalizeApiError(e).message)}finally{setBusy(false)}}
  async function toggle(topic:Topic){setBusy(true);try{await setTopicActive(topic.id,!topic.isActive);setLifecycle(null);await load()}catch(e){setError(normalizeApiError(e).message)}finally{setBusy(false)}}
  return <PageContainer><PageHeader title="مدیریت موضوع‌ها" description="کاتالوگ سراسری موضوع‌های قابل استفاده در پایش" actions={<Button onClick={()=>setEditing('create')}><Plus size={18}/>موضوع جدید</Button>}/><form className="workspace-toolbar" onSubmit={e=>{e.preventDefault();setPage(1);setSearch(new FormData(e.currentTarget).get('search')?.toString().trim()??'')}}><Input name="search" aria-label="جست‌وجوی موضوع" placeholder="نام، کد یا نام جایگزین"/><Button type="submit" variant="secondary">جست‌وجو</Button></form>{loading?<PageLoading label="در حال دریافت موضوع‌ها…"/>:error?<PageError description={error} onRetry={()=>void load()}/>:result.data.length===0?<EmptyState title="موضوعی یافت نشد" description="اولین موضوع را ایجاد کنید." icon={<Tags size={30}/>}/>:<><div className="workspace-grid">{result.data.map(topic=><SurfaceCard className="workspace-card language-card" key={topic.id}><header><strong>{topic.name}</strong><Badge tone={topic.isActive?'success':'warning'}>{topic.isActive?'فعال':'غیرفعال'}</Badge></header><div><code dir="ltr">{topic.code}</code><p>{topic.description||'بدون توضیح'}</p><small>{topic.domains.map(domain=>domain.name).join('، ')||'بدون حوزه'} · {topic.aliases.length} نام جایگزین</small></div><footer><Button variant="ghost" onClick={()=>setEditing(topic)}><Pencil size={17}/>ویرایش</Button><Button variant="ghost" onClick={()=>setLifecycle(topic)}><Power size={17}/>{topic.isActive?'غیرفعال‌سازی':'فعال‌سازی'}</Button></footer></SurfaceCard>)}</div><nav className="workspace-pagination"><Button variant="secondary" disabled={!result.meta.hasPrevious} onClick={()=>setPage(p=>p-1)}>قبل</Button><span>صفحه {page} از {Math.max(result.meta.totalPages,1)}</span><Button variant="secondary" disabled={!result.meta.hasNext} onClick={()=>setPage(p=>p+1)}>بعد</Button></nav></>}{editing&&<Modal title={editing==='create'?'افزودن موضوع':'ویرایش موضوع'} onClose={()=>!busy&&setEditing(null)}><TopicForm topic={editing==='create'?undefined:editing} busy={busy} error={formError} onSubmit={save} onCancel={()=>setEditing(null)}/></Modal>}{lifecycle&&<Modal title={lifecycle.isActive?'غیرفعال‌سازی موضوع':'فعال‌سازی موضوع'} description={lifecycle.isActive?'اتصال‌های موجود حفظ می‌شوند، اما موضوع برای انتخاب جدید در دسترس نیست.':'موضوع دوباره قابل انتخاب خواهد بود.'} onClose={()=>!busy&&setLifecycle(null)}><div className="archive-confirmation"><footer><Button variant="secondary" onClick={()=>setLifecycle(null)}>انصراف</Button><Button variant={lifecycle.isActive?'danger':'primary'} disabled={busy} onClick={()=>void toggle(lifecycle)}>تأیید</Button></footer></div></Modal>}</PageContainer>
}

function TopicForm({topic,busy,error,onSubmit,onCancel}:{topic?:Topic;busy:boolean;error:string|null;onSubmit:(input:CreateTopicInput)=>Promise<void>;onCancel:()=>void}){
  const[code,setCode]=useState(topic?.code??''),[name,setName]=useState(topic?.name??''),[description,setDescription]=useState(topic?.description??''),[domainIds,setDomainIds]=useState(topic?.domains.map(domain=>domain.id)??[]),[aliases,setAliases]=useState<TopicAliasInput[]>(topic?.aliases.map(alias=>({value:alias.value,languageId:alias.languageId}))??[]),[domains,setDomains]=useState<IntelligenceDomain[]>(topic?.domains??[]),[languages,setLanguages]=useState<Language[]>(topic?.aliases.flatMap(alias=>alias.language?[alias.language]:[])??[]),[catalogError,setCatalogError]=useState<string|null>(null)
  useEffect(()=>{void Promise.all([listAllSelectableIntelligenceDomains(),listAllSelectableLanguages()]).then(([activeDomains,activeLanguages])=>{setDomains([...new Map([...activeDomains,...(topic?.domains??[])].map(item=>[item.id,item])).values()]);setLanguages([...new Map([...activeLanguages,...(topic?.aliases.flatMap(alias=>alias.language?[alias.language]:[])??[])].map(item=>[item.id,item])).values()])}).catch(e=>setCatalogError(normalizeApiError(e).message))},[topic])
  function patchAlias(index:number,patch:Partial<TopicAliasInput>){setAliases(current=>current.map((alias,i)=>i===index?{...alias,...patch}:alias))}
  return <form className="workspace-form" onSubmit={e=>{e.preventDefault();void onSubmit({code:code.trim().toLowerCase().replace(/[\s_]+/g,'-'),name:name.trim(),description:description.trim()||undefined,domainIds,aliases:aliases.filter(alias=>alias.value.trim()).map(alias=>({...alias,value:alias.value.trim()}))})}}><Label>کد<Input dir="ltr" required maxLength={100} readOnly={Boolean(topic)} value={code} onChange={e=>setCode(e.target.value)}/></Label><Label>نام canonical<Input required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></Label><Label>توضیح<Input maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)}/></Label><fieldset className="language-multi"><legend>حوزه‌ها</legend><div>{domains.map(domain=><label key={domain.id}><input type="checkbox" checked={domainIds.includes(domain.id)} onChange={()=>setDomainIds(domainIds.includes(domain.id)?domainIds.filter(id=>id!==domain.id):[...domainIds,domain.id])}/><span>{domain.name}</span><small>{domain.code}{!domain.isActive?' — غیرفعال':''}</small></label>)}</div></fieldset><fieldset className="language-multi"><legend>نام‌های جایگزین</legend>{aliases.map((alias,index)=><div className="topic-alias-row" key={index}><Input aria-label={`نام جایگزین ${index+1}`} value={alias.value} onChange={e=>patchAlias(index,{value:e.target.value})}/><select className="ui-input" aria-label={`زبان نام جایگزین ${index+1}`} value={alias.languageId??''} onChange={e=>patchAlias(index,{languageId:e.target.value||null})}><option value="">بدون زبان</option>{languages.map(language=><option key={language.id} value={language.id}>{language.nativeName} ({language.code}){!language.isActive?' — غیرفعال':''}</option>)}</select><Button type="button" variant="ghost" aria-label="حذف نام جایگزین" onClick={()=>setAliases(current=>current.filter((_,i)=>i!==index))}><Trash2 size={16}/></Button></div>)}<Button type="button" variant="secondary" onClick={()=>setAliases(current=>[...current,{value:'',languageId:null}])}><Plus size={16}/>افزودن نام جایگزین</Button></fieldset>{(error||catalogError)&&<div className="form-error" role="alert">{error||catalogError}</div>}<footer><Button type="button" variant="secondary" onClick={onCancel}>انصراف</Button><Button type="submit" disabled={busy||Boolean(catalogError)}>{busy?'در حال ذخیره…':'ذخیره'}</Button></footer></form>
}
