import { useCallback, useEffect, useState } from 'react'
import { Boxes, Pencil, Plus, Power } from 'lucide-react'
import { Modal } from '@/components/Modal'
import { EmptyState, PageContainer, PageError, PageHeader, PageLoading } from '@/components/PageStates'
import { Badge, Button, Input, Label, SurfaceCard } from '@/components/ui'
import { normalizeApiError } from '@/lib/apiError'
import { createIntelligenceDomain, listIntelligenceDomains, setIntelligenceDomainActive, updateIntelligenceDomain } from './intelligenceDomainApi'
import type { CreateIntelligenceDomainInput, IntelligenceDomain, IntelligenceDomainPage } from './intelligenceDomainTypes'

const empty: IntelligenceDomainPage = { data: [], meta: { total: 0, page: 1, limit: 20, totalPages: 0, hasNext: false, hasPrevious: false } }
export function IntelligenceDomainAdminPage() {
  const [result,setResult]=useState(empty),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[search,setSearch]=useState(''),[page,setPage]=useState(1),[editing,setEditing]=useState<IntelligenceDomain|'create'|null>(null),[busy,setBusy]=useState(false),[formError,setFormError]=useState<string|null>(null),[lifecycleTarget,setLifecycleTarget]=useState<IntelligenceDomain|null>(null)
  const load=useCallback(async()=>{setLoading(true);setError(null);try{setResult(await listIntelligenceDomains({page,limit:20,search:search||undefined},true))}catch(e){setError(normalizeApiError(e).message)}finally{setLoading(false)}},[page,search])
  useEffect(()=>{void load()},[load])
  async function save(input:CreateIntelligenceDomainInput){setBusy(true);setFormError(null);try{editing==='create'?await createIntelligenceDomain(input):editing&&await updateIntelligenceDomain(editing.id,{name:input.name,description:input.description||null});setEditing(null);await load()}catch(e){setFormError(normalizeApiError(e).message)}finally{setBusy(false)}}
  async function toggle(domain:IntelligenceDomain){setBusy(true);try{await setIntelligenceDomainActive(domain.id,!domain.isActive);setLifecycleTarget(null);await load()}catch(e){setError(normalizeApiError(e).message)}finally{setBusy(false)}}
  return <PageContainer><PageHeader title="مدیریت حوزه‌ها" description="کاتالوگ سراسری حوزه‌های معنایی پایش" actions={<Button onClick={()=>setEditing('create')}><Plus size={18}/>حوزه جدید</Button>}/><form className="workspace-toolbar" onSubmit={e=>{e.preventDefault();setPage(1);setSearch(new FormData(e.currentTarget).get('search')?.toString().trim()??'')}}><Input name="search" aria-label="جست‌وجوی حوزه" placeholder="نام، توضیح یا کد"/><Button type="submit" variant="secondary">جست‌وجو</Button></form>{loading?<PageLoading label="در حال دریافت حوزه‌ها…"/>:error?<PageError description={error} onRetry={()=>void load()}/>:result.data.length===0?<EmptyState title="حوزه‌ای یافت نشد" description="اولین حوزه را به کاتالوگ اضافه کنید." icon={<Boxes size={30}/>}/>:<><div className="workspace-grid">{result.data.map(domain=><SurfaceCard className="workspace-card language-card" key={domain.id}><header><strong>{domain.name}</strong><Badge tone={domain.isActive?'success':'warning'}>{domain.isActive?'فعال':'غیرفعال'}</Badge></header><div><code dir="ltr">{domain.code}</code><p>{domain.description||'بدون توضیح'}</p></div><footer><Button variant="ghost" onClick={()=>setEditing(domain)}><Pencil size={17}/>ویرایش</Button><Button variant="ghost" disabled={busy} onClick={()=>setLifecycleTarget(domain)}><Power size={17}/>{domain.isActive?'غیرفعال‌سازی':'فعال‌سازی'}</Button></footer></SurfaceCard>)}</div><nav className="workspace-pagination"><Button variant="secondary" disabled={!result.meta.hasPrevious} onClick={()=>setPage(p=>p-1)}>قبل</Button><span>صفحه {page} از {Math.max(result.meta.totalPages,1)}</span><Button variant="secondary" disabled={!result.meta.hasNext} onClick={()=>setPage(p=>p+1)}>بعد</Button></nav></>}{editing&&<Modal title={editing==='create'?'افزودن حوزه':'ویرایش حوزه'} onClose={()=>!busy&&setEditing(null)}><DomainForm domain={editing==='create'?undefined:editing} busy={busy} error={formError} onSubmit={save} onCancel={()=>setEditing(null)}/></Modal>}{lifecycleTarget&&<Modal title={lifecycleTarget.isActive?'غیرفعال‌سازی حوزه':'فعال‌سازی حوزه'} description={lifecycleTarget.isActive?'ارجاع‌های موجود حفظ می‌شوند، اما حوزه برای انتخاب جدید در دسترس نخواهد بود.':'حوزه دوباره برای انتخاب جدید قابل استفاده می‌شود.'} onClose={()=>!busy&&setLifecycleTarget(null)}><div className="archive-confirmation"><footer><Button variant="secondary" onClick={()=>setLifecycleTarget(null)}>انصراف</Button><Button variant={lifecycleTarget.isActive?'danger':'primary'} disabled={busy} onClick={()=>void toggle(lifecycleTarget)}>تأیید</Button></footer></div></Modal>}</PageContainer>
}
function DomainForm({domain,busy,error,onSubmit,onCancel}:{domain?:IntelligenceDomain;busy:boolean;error:string|null;onSubmit:(input:CreateIntelligenceDomainInput)=>Promise<void>;onCancel:()=>void}){const[code,setCode]=useState(domain?.code??''),[name,setName]=useState(domain?.name??''),[description,setDescription]=useState(domain?.description??'');return <form className="workspace-form" onSubmit={e=>{e.preventDefault();void onSubmit({code:code.trim().toLowerCase().replace(/[\s_]+/g,'-'),name:name.trim(),description:description.trim()||undefined})}}><Label>کد<Input dir="ltr" required maxLength={80} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" readOnly={Boolean(domain)} value={code} onChange={e=>setCode(e.target.value)}/></Label><Label>نام<Input required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></Label><Label>توضیح<Input maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)}/></Label>{error&&<div className="form-error" role="alert">{error}</div>}<footer><Button type="button" variant="secondary" onClick={onCancel}>انصراف</Button><Button type="submit" disabled={busy}>{busy?'در حال ذخیره…':'ذخیره'}</Button></footer></form>}
